{
 "title": "Rinnegan",
 "description": "Eye that sees it all!!",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES WITH key = \"hostname\""
   },
   {
    "name": "type",
    "label": "Type",
    "query": "SHOW TAG VALUES WITH key = \"type\""
   },
   {
    "name": "syscall",
    "label": "Syscalls",
    "query": "SHOW TAG VALUES WITH key = \"syscall\""
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "SHOW TAG VALUES WITH key = \"protocol\";"
   }
  ]
 },
 "panels": [
  {
   "title": "interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interfaces",
     "type": "table",
     "description": "Interfaces of targets on which agents are running",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT hostname,interface,ip FROM \"agent\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "sockets",
     "type": "table",
     "description": "TCP, UDP & Unix listening sockets",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT hostname,ip,port,protocol,pid,type FROM \"socket\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ps ($host)",
     "type": "table",
     "description": "Process listing",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "repeat": "host",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "VA-lca1-b1-stg-esx01-stage-linkedin-biz-director",
       "query": "SELECT \"pid\", \"ppid\", \"user\", \"command\" FROM \"process\" WHERE \"hostname\" = '$host' ORDER BY time DESC",
       "select": [
        [
         { "params": [ "pid" ], "type": "field" }
        ],
        [
         { "params": [ "ppid" ], "type": "field" }
        ],
        [
         { "params": [ "user" ], "type": "field" }
        ],
        [
         { "params": [ "command" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "syscall - ($syscall)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "syscall",
   "collapsed": true,
   "panels": [
    {
     "title": "$host- Syscall",
     "type": "table",
     "description": "Syscalls",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "repeat": "host",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "VA-lca1-b1-stg-esx01-stage-linkedin-biz-director",
       "query": "SELECT \"pid\", \"syscall\", \"arg0\", \"arg1\", \"arg2\", \"return\" FROM \"syscall\" WHERE \"hostname\" = '$host' AND \"syscall\" = '$syscall' AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "pid" ], "type": "field" }
        ],
        [
         { "params": [ "ppid" ], "type": "field" }
        ],
        [
         { "params": [ "user" ], "type": "field" }
        ],
        [
         { "params": [ "command" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network Tracing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Network (OUT)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "send",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"return\") FROM \"syscall\" WHERE $timeFilter AND \"hostname\" = '$host' AND \"syscall\" =~ /send/ GROUP BY time($__interval),pid fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"return\") FROM \"syscall\" WHERE $timeFilter AND \"hostname\" = '$host' AND \"syscall\" =~ /write/ GROUP BY time($__interval),pid fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$host - Network (IN)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "recv",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"return\") FROM \"syscall\" WHERE $timeFilter AND \"hostname\" = '$host' AND \"syscall\" =~ /recv/ GROUP BY time($__interval),pid fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"return\") FROM \"syscall\" WHERE $timeFilter AND \"hostname\" = '$host' AND \"syscall\" =~ /read/ GROUP BY time($__interval),pid fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$host- Tracing",
     "type": "table",
     "description": "Tracers",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "repeat": "host",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "VA-lca1-b1-stg-esx01-stage-linkedin-biz-director",
       "query": "SELECT \"pid\", \"syscall\", \"arg0\", \"arg1\", \"arg2\", \"return\" FROM \"syscall\" WHERE \"hostname\" = '$host' AND $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "pid" ], "type": "field" }
        ],
        [
         { "params": [ "ppid" ], "type": "field" }
        ],
        [
         { "params": [ "user" ], "type": "field" }
        ],
        [
         { "params": [ "command" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "$host - SSL Tracing",
     "type": "table",
     "description": "SSL Tracing",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "repeat": "host",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "VA-lca1-b1-stg-esx01-stage-linkedin-biz-director",
       "query": "SELECT pid,libcall,\"arg0\",\"arg1\" FROM \"$host\" WHERE $timeFilter AND \"type\" = 'libcall' ORDER BY time DESC",
       "select": [
        [
         { "params": [ "pid" ], "type": "field" }
        ],
        [
         { "params": [ "ppid" ], "type": "field" }
        ],
        [
         { "params": [ "user" ], "type": "field" }
        ],
        [
         { "params": [ "command" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}